"""Extract a non-destructive init script from the user's authoritative database.sql.

Run from any directory: python backend/scripts/prepare_database.py
The output is for a selected NEW database. Existing databases require migration.
"""
from pathlib import Path
import re

backend = Path(__file__).resolve().parents[1]
source = (backend / "database.sql").read_text(encoding="utf-8-sig")
# Remove database-level reset/routing statements only; keep tables, indexes and inserts.
source = re.sub(r"(?im)^DROP DATABASE\b[^;]*;", "", source)
source = re.sub(r"(?ims)^CREATE DATABASE\b.*?;", "", source)
source = re.sub(r"(?im)^USE\s+\w+\s*;", "", source)
source = re.sub(r"(?ims)^SELECT\s+TABLE_NAME\s+FROM information_schema\.TABLES.*?;", "", source)
assert len(re.findall(r"(?im)^CREATE TABLE ", source)) == 25
assert not re.search(r"(?im)^(DROP|TRUNCATE|DELETE|USE)\b", source)
output = backend / "docker" / "init.sql"
output.parent.mkdir(exist_ok=True)
output.write_text("-- Generated by scripts/prepare_database.py; import only into a NEW selected database.\n" + source, encoding="utf-8")
print("Prepared docker/init.sql: 25 tables; no database reset statements.")
